version: '3.9'

services:
  database:
    image: postgres:12-alpine
    container_name: database
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=testpw
      - POSTGRES_DB=practice
    ports:
      - 5432:5432
